### ISSUE TITLE
Incompatibility FancyHud with AppleSkin, Elenai Dodge 2, Scaling Health | 1.16.5

### ISSUE THREAD

**Issue by DoDoSov** [Keksuccino/FancyHud#3]
Screenshots:
https://ibb.co/wyvb9Mw
https://ibb.co/RyyctkF
--------------------------------------
When I install FancyHud, my Hud makes very awful. If I go to change the place of elements. 

As a Result I can`t do this because some elements not highlight (as example : Health Bar from Scaling Health, Food Bar from AppleSkin, Sprint Bar from Elenai Dodge)

If I play minecraft without FancyHud - My Hud takes Normal:
https://ibb.co/9GJyL8r

**Comment by Keksuccino** [comment]
Hi!

Sadly that's not something I can fix on my end. The devs of these mods need to add support for FH on their end.

Here's a link to the FancyHud API: https://github.com/Keksuccino/FancyHud/wiki/FancyHud-API
