### ISSUE TITLE
Armor bar not modifiable

### ISSUE THREAD

**Issue by AuroraHydroid** [Keksuccino/FancyHud#8]
The vanilla armor bar is not modifiable in the Fancy Hud interface. I cannot click and drag it to move it.

**Comment by Keksuccino** [comment]
Hi! You probably have a mod installed that is modifying this bar, that's why FancyHud can't customize it. You need to remove the other mod if you want to customize this bar.

**Comment by Keksuccino** [comment]
If you can select it in the editor (so if you just can't move it), try to right-click it and disable the option that allows other mods to customize this element. That way you should be able to keep the other mod installed.

**Comment by AuroraHydroid** [comment]
I will try that! thank you for the reply.

**Comment by AuroraHydroid** [comment]
Worked a treat, thank you! Turned off the mod customization.
